# Generated by Django 3.2 on 2021-05-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Введите название соревнования', max_length=100)),
                ('desc', models.TextField(help_text='Введите описание соревнования')),
                ('state', models.CharField(default='w', help_text='Укажите состояние, в котором находится соревнование', max_length=1)),
                ('date_of_start', models.DateTimeField()),
                ('date_of_finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.user')),
                ('competition', models.ManyToManyField(to='catalog.Competition')),
            ],
        ),
    ]
