# Generated by Django 3.2 on 2021-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_student_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='competition',
            field=models.ManyToManyField(to='catalog.Competition'),
        ),
    ]
