# Generated by Django 3.2 on 2021-06-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210603_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.teacher'),
        ),
    ]
