# Generated by Django 3.2 on 2021-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210605_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupe',
            field=models.CharField(help_text='Укажите номер группы в формате 00-000', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='competition',
            field=models.ManyToManyField(related_name='competitions', to='catalog.Competition'),
        ),
    ]
