# Generated by Django 3.2 on 2021-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210610_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='competitionfile',
            name='file',
        ),
        migrations.AddField(
            model_name='answerfile',
            name='data_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='answerfile',
            name='model_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='competition',
            name='complexity',
            field=models.CharField(choices=[('e', 'Легкий'), ('n', 'Средний'), ('d', 'Сложный')], default='w', help_text='Укажите состояние, в котором находится соревнование', max_length=1),
        ),
        migrations.AddField(
            model_name='competitionfile',
            name='data_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='competitionfile',
            name='test_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='state',
            field=models.CharField(choices=[('w', 'Будет'), ('n', 'Идет'), ('f', 'Завершилось')], default='w', help_text='Укажите состояние, в котором находится соревнование', max_length=1),
        ),
    ]
