# Generated by Django 3.2 on 2021-06-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210610_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='complexity',
            field=models.CharField(choices=[('e', 'Легкий'), ('n', 'Средний'), ('d', 'Сложный')], default='e', help_text='Укажите сложность соревнования', max_length=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='state',
            field=models.CharField(choices=[('w', 'Планируется'), ('n', 'Проходит'), ('f', 'Завершилось')], default='w', help_text='Укажите состояние, в котором находится соревнование', max_length=1),
        ),
        migrations.CreateModel(
            name='ColabHref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=150)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_colab', to='catalog.competition')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_colab', to='catalog.student')),
            ],
        ),
    ]
