# Generated by Django 3.2 on 2021-06-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210615_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionfile',
            name='true_answer_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
