# Generated by Django 3.2 on 2021-06-17 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_competitionfile_true_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_of_finish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_of_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
