# Generated by Django 3.2 on 2021-06-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210617_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
