# Generated by Django 3.2 on 2021-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_answerfile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfile',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
